{% set name = "pycsep" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: 883acac2fd14f207585b661acd945b48a1a8adca1d377a429260831da08f8f30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cartopy
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyproj
    - python >={{ python_min }}
    - python-dateutil
    - scipy
    - shapely
    - mercantile

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wsavran
    - pjmaechling
    - fabiolsilva
    - pabloitu
